---
title: "Compare two artists"
author: "Yuhong Fang"
date: "3/18/2020"
output: html_document
---

```{r}
library(spotifyr)
library(tidyverse)
library(fmsb)
library(shiny)
library(ggplot2)
library(dplyr)
library(plotly)

Sys.setenv(SPOTIFY_CLIENT_ID = 'f0d212500a7e4c74baaab9025ea186c3')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '4985198dd20d47c7bdc5e52a1cf01e3f')

access_token <- get_spotify_access_token()
```

```{r}
ui = fluidPage(
  sidebarPanel(
    textInput(inputId = "artist1", 
            label = "First Artist:"),
    textInput(inputId = "artist2", 
            label = "Second Artist:")
  ),
  mainPanel(
    plotOutput("radar"),
    tableOutput("summary")
  )
)

server = function(input, output){
  # Based on the name typed in, find the most popular artist
  name_artist1 = reactive({
    (search_spotify(input$artist1, type="artist") %>% arrange(desc(popularity)) %>% select(name))[1,1]
    })
  name_artist2 = reactive({
    (search_spotify(input$artist2, type="artist") %>% arrange(desc(popularity)) %>% select(name))[1,1]
  })
  artist_1 = get_artist_audio_features(as.character(name_artist1))[,c(1,2,3,7,9,10,11,12,14,15,16,17,18,19,20,26,30,36,37,38,39)] # artist name, artist id, album id, album release year, danceability, energy, key, loudness, speechiness, acounsticness, instrumentalness, liveness, valence, tempo, track id, duration(ms), track name, key name, mode name, key mode
  artist_2 = get_artist_audio_features(as.character(name_artist2))[,c(1,2,3,7,9,10,11,12,14,15,16,17,18,19,20,26,30,36,37,38,39)]
  
  artist_1_means = artist_1 %>% select(danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms, key) %>% summarise_all(funs(mean))
  artist_1_summary = get_artist(artist_1$artist_id[1])
  artist_1_summary = cbind(artist_1_means, data.frame(genres = artist_1_summary$genres[1], total_followers = artist_1_summary$followers$total, popularity = artist_1_summary$popularity))
  artist_2_means = artist_2 %>% select(danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms, key) %>% summarise_all(funs(mean))
  artist_2_summary = get_artist(artist_2$artist_id[1])
  artist_2_summary = cbind(artist_2_means, data.frame(genres = artist_2_summary$genres[1], total_followers = artist_2_summary$followers$total, popularity = artist_2_summary$popularity))
  
  output$summary = renderTable(
    artist_1_summary,
    artist_2_summary
  )
  
  output$radar = renderplot({
        artist_radar = rbind(artist_1_summary, artist_2_summary) %>% select(danceability,energy, acousticness, valence, loudness) %>% mutate(loudness = loudness / -60)
        colnames(artist_radar) = c('Danceability', 'Energy', 'Acousticness', 'Valence', 'loudness') 
        reactive({rownames(artist_radar) = c(name_artist1, name_artist2)})
        artist_radar <- rbind(rep(1,5) , rep(0,5) , artist_radar)
        
        col_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
        col_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4) , rgb(0.7,0.5,0.1,0.4) )
        
        radarchart(artist_radar, axistype=1, 
                   #custom polygon
                   pcol= col_border , pfcol=col_in , plwd=4 , plty = 1,
                   #custom the grid
                   cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,1,5), cglwd=0.8,
                   #custom labels
                   vlcex=0.8 )
  })
}

shinyApp(ui = ui, server = server)
```